scripts/appliance-report.py: Use mount_ro
Witout this, when running on el7, mount fails with:
=======================================================================
  File "/usr/lib64/python2.7/site-packages/guestfs.py", line 7477, in
mount
r = libguestfsmod.mount(self._o, mountable, mountpoint)
RuntimeError: mount: mount exited with status 32: mount: wrong fs type,
bad option, bad superblock on /dev/mapper/ovirt-var,
missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
dmesg | tail or so.
=======================================================================

'dmesg | tail' shows:
=======================================================================
[ 1533.899970] XFS (dm-6): Superblock has unknown read-only compatible
features (0x4) enabled.
[ 1533.907362] XFS (dm-6): Attempted to mount read-only compatible
filesystem read-write.
[ 1533.907369] XFS (dm-6): Filesystem can only be safely mounted read
only.
[ 1533.907378] XFS (dm-6): SB validate failed with error -22.
=======================================================================

I guess this is a result of the 4.4 appliance being created on
el8 and using newer, el7-incompatible options.

Change-Id: I3d5de480389b243fc04f4583de3111aacdc10885
Signed-off-by: Yedidyah Bar David <didi@redhat.com>